<Project>
  <PropertyGroup>
    <Version>2.8.0-dev.1</Version>
    <Company>Cert Generator</Company>
    <Product>Cert Generator Pal</Product>
    <Copyright>darthrater78/cert-generator</Copyright>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <Deterministic>true</Deterministic>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
</Project>
